#!/bin/bash

# STRUCTURE
# /Build
# |
# +-- /components
# |   |
# |   +-- headContent.html
# |
# +-- /content
# |   |
# |   +-- color_palettes-1.html
# |   +-- css_selectors_table-1.html
# |   +-- html_structure_example-1.html
# |
# +-- /css
# |   |
# |   +-- style.css
# |
# +-- /img
# |   |
# |   +-- /favicon
# |   |   |
# |   |   +-- android-chrome-192x192.png
# |   |   +-- android-chrome-512x512.png
# |   |   +-- apple-touch-icon.png
# |   |   +-- favicon-16x16.png
# |   |   +-- favicon-32x32.png
# |   |   +-- favicon.ico
# |   |   +-- manifest.json
# |   |
# |   +-- Logo_Mobit_Hand_Inverted.svg
# |   +-- Logo_Mobit_Hand.svg
# |   +-- Logo_Mobit_Inverted.svg
# |   +-- Logo_Mobit.svg
# |
# +-- /scripts
# |   |
# |   +-- main.js
# |
# +-- favicon.ico
# +-- index.php



# Starting routine
echo "Starting build routine..."

# Establish build directory target
TARGET="Build"

INCLUDE_FILES="index.php favicon.ico"
INCLUDE_DIR="components"

# Clear target content
echo "Clear $TARGET/ content"
rm -r $TARGET/*

# Make necessary directories
DIR="$TARGET/$INCLUDE_DIR"
echo "Create $DIR/"
mkdir $DIR

echo "Copy ${INCLUDE_DIR/*} to $DIR/"
cp $INCLUDE_DIR/* $DIR

# Move files to Build
echo "Copy $INCLUDE_FILES to $TARGET/"
cp $INCLUDE_FILES $TARGET

# Ending routine
echo "Build routine complete"